# Generated by Django 5.2.14 on 2026-06-08 18:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('board_game', 'Board game'), ('ttrpg', 'TTRPG asset'), ('tcg', 'TCG'), ('office', 'Office'), ('other', 'Other')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('thumbnail_ref', models.CharField(blank=True, max_length=500)),
                ('image_ref', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_pt', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_es', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name_pt'],
            },
        ),
        migrations.CreateModel(
            name='TtrpgAsset',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('system', models.CharField(choices=[('dnd', 'Dungeons & Dragons'), ('pathfinder', 'Pathfinder'), ('lotr', 'The Lord of the Rings'), ('other', 'Other')], max_length=32)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TTRPG asset',
                'verbose_name_plural': 'TTRPG assets',
            },
            bases=('inventory.item',),
        ),
        migrations.CreateModel(
            name='ItemCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(blank=True, max_length=200)),
                ('hidden', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='inventory.item')),
            ],
            options={
                'verbose_name': 'item copy',
                'verbose_name_plural': 'item copies',
            },
        ),
        migrations.CreateModel(
            name='GameNightGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gamenight_games', to='inventory.itemcopy')),
            ],
            options={
                'ordering': ['-date', 'copy__item__name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='inventory.itemcopy')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='inventory.person')),
            ],
            options={
                'ordering': ['-checkout_time'],
            },
        ),
        migrations.AddField(
            model_name='itemcopy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_copies', to='inventory.person'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='inventory.tag'),
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('bgg_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('min_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opt_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_playtime_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_playtime_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('parent_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expansions', to='inventory.boardgame')),
            ],
            options={
                'verbose_name': 'board game',
                'verbose_name_plural': 'board games',
            },
            bases=('inventory.item',),
        ),
        migrations.CreateModel(
            name='GameNightRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('times', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gamenight_requests', to='inventory.item')),
            ],
            options={
                'ordering': ['-date', 'item__name'],
                'constraints': [models.UniqueConstraint(fields=('date', 'item'), name='unique_gamenight_request')],
            },
        ),
    ]
