# Generated by Django 5.2.14 on 2026-08-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
